In [5]:
import numpy as np

This command shows helpful information about numpy.

In [6]:
np?

This type of cell is a markdown cell. It shows explanatory text. The code below prints the output, but this is not necessary since Jupyter shows the output for you.

In [7]:
result = 0
for i in range(100):
    result += i
    print(result)

0
1
3
6
10
15
21
28
36
45
55
66
78
91
105
120
136
153
171
190
210
231
253
276
300
325
351
378
406
435
465
496
528
561
595
630
666
703
741
780
820
861
903
946
990
1035
1081
1128
1176
1225
1275
1326
1378
1431
1485
1540
1596
1653
1711
1770
1830
1891
1953
2016
2080
2145
2211
2278
2346
2415
2485
2556
2628
2701
2775
2850
2926
3003
3081
3160
3240
3321
3403
3486
3570
3655
3741
3828
3916
4005
4095
4186
4278
4371
4465
4560
4656
4753
4851
4950


In [8]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [11]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Numpy arrays can be multidimensional, but Python lists cannot.

In [13]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3, 5), dtype = float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [17]:
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

start, stop, skip

In [19]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

create an array of values evenly spaced between 0 and 1

In [20]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

create a 3x3 array of values in between 0 and 1

In [21]:
np.random.random((3, 3))

array([[ 0.47037288,  0.08659961,  0.59001463],
       [ 0.21428705,  0.38039285,  0.38359576],
       [ 0.49660911,  0.94559859,  0.36735649]])

create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1

In [22]:
np.random.normal(0, 1, (3, 3))

array([[ 2.04676347, -0.37809697, -0.02410604],
       [-0.50952793, -0.61096315, -0.7177086 ],
       [-1.02643503, -1.3581004 , -1.8763231 ]])

create a 3x3 array of random integers in the interval [0, 10)

In [23]:
np.random.randint(0, 10, (3, 3))

array([[1, 5, 0],
       [8, 1, 1],
       [4, 4, 2]])

create a 3x3 indentity matrix

In [24]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

create an unitialized array of 3 integers where the values will be whatever happens to already exist in that memory

In [25]:
np.empty(3)

array([ 1.,  1.,  1.])